[tool.poetry]
name = "segdtw"
version = "0.1.0"
description = ""
authors = ["stegben <stegben.benjamin@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.5"
numpy = "^1.18.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
